#!/bin/bash

shopt -s nullglob globstar

# Should the entry/field be typed instead of copied?
typeit=0
autotypeit=0
if [[ $1 == "--type" ]]; then
    typeit=1
elif [[ $1 == "--autotype" ]]; then
    autotypeit=1
fi

# Load $DMENU_OPTIONS
if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
fi
dmenu_cmd="dmenu $DMENU_OPTIONS -l 20 -w 500"

# Use custom pass directory, if set
prefix=${PASSWORD_STORE_DIR-~/.password-store}

# List entries (directories with .gpg files)
pass_entries=($(ls "$prefix"/**/*.gpg | xargs dirname | uniq))
pass_entries=("${pass_entries[@]#"$prefix"/}")
entry=$(printf "%s\n" "${pass_entries[@]}" | $dmenu_cmd -p "pass entry")
[[ -n $entry ]] || exit

typefield () {
    pass show "$1" | { IFS= read -r pass; printf %s "$pass"; } |
        xdotool type --clearmodifiers --file -
}

if [[ $autotypeit -eq 1 ]]; then
    # Type fields `username` and `password` from entry
    username="$entry/username"
    password="$entry/password"
    typefield "$username"
    xdotool key Tab
    typefield "$password"
    xdotool key Return
else
    # List available fields (.gpg files)
    field=$(pass ls "$entry" | tail -n+2 | sed -E 's/^\W+//' |
                $dmenu_cmd -p "entry field")
    [[ -n $field ]] || exit

    password="$entry/$field"

    if [[ $typeit -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
    else
        typefield "$password"
    fi
fi
